### ISSUE TITLE
Other Colored Spell Icons

### ISSUE THREAD

**Issue by UltimaScripts** [CorvaeOboro/ultima_online_mods#1]
Is there any chance you can colorize the other necro spell icons? 
Also can you do Spellweaving icons?

I really like your color icon style the best.

**Comment by CorvaeOboro** [comment]
Thank you , we have recently updated the art mod to include colorized spells icons for all spells and abilities including Necromancy , Mysticism , SpellWeaving , Mastery , Combat , Bushido , and Ninjitsu . 

![SpellsColorizedA](https://raw.githubusercontent.com/CorvaeOboro/ultima_online_mods/main/UI/00_ui_comp_spells_gif_A.png)
![SpellsColorizedB](https://raw.githubusercontent.com/CorvaeOboro/ultima_online_mods/main/UI/00_ui_comp_spells_gif_B.png)
![SpellsColorizedC](https://raw.githubusercontent.com/CorvaeOboro/ultima_online_mods/main/UI/00_ui_comp_spells_gif_C.png)
